_format_version: "1.1"
services:
- name: Service
  url: http://httpbin.org:80
  plugins: []
  routes:
  - tags:
    - OAS3_import
    name: route1
    methods:
    - GET
    paths:
    - /route
    strip_path: true
  tags:
  - OAS3_import