_format_version: "1.1"
services:
- name: Service1
  url: https://restcountries.eu/rest/v2/alpha/th
  plugins: []
  routes:
  - tags:
    - OAS3_import
    name: route1
    methods:
    - GET
    paths:
    - /route1
    strip_path: true
  tags:
  - OAS3_import